### ISSUE TITLE
Описание проекта

### ISSUE THREAD

**Issue by kikozavr** [simlex-titul2005/SX.WebCore#10]
В этом документе будет располагаться исчерпывающая информация по данному проекту.

**Comment by kikozavr** [comment]
Назначение проекта: 
Проект разработан как библиотека, в которой содержатся различные механизмы, упрощающие создание качественных веб-сайтов.

**Comment by kikozavr** [comment]
## Размещение проекта:
Проект размещен в виде сборки(Solution), созданной в IDE MS Visual Studio
Microsoft Visual Studio Solution File, Format Version 12.00
Visual Studio 14
VisualStudioVersion = 14.0.25420.1
MinimumVisualStudioVersion = 10.0.40219.1
.net framework 4.6.1
Хранилище (Repository) сборки опубликовано на ресурсе GitHub и доступно по ссылке: https://github.com/simlex-titul2005/SX.WebCore

**Comment by simlex-titul2005** [comment]
Описание проекта нужно делать в wiki. В issue должы быть только задачи
